import { Request, Response } from 'express';
import {
  getWorkOrdersDb,
  createWorkOrderDb,
  updateWorkOrderDb,
  getEquipmentDb,
} from '../../../database/models/store';

export async function getWorkOrders(req: Request, res: Response) {
  try {
    const workOrders = await getWorkOrdersDb();
    return res.json({ success: true, workOrders });
  } catch (error: any) {
    return res.status(500).json({ success: false, error: error.message || 'Failed to fetch work orders' });
  }
}

export async function createWorkOrder(req: Request, res: Response) {
  try {
    const { title, equipmentId, equipmentName, priority, assignedTechnician, description } = req.body;

    const newWo = {
      id: `WO-2026-${Math.floor(1000 + Math.random() * 9000)}`,
      createdAt: new Date().toISOString().replace('T', ' ').substring(0, 16),
      status: 'Open',
      facilityId: req.body.facilityId || 'apex-hq',
      assetId: equipmentId || req.body.assetId || 'CHILLER-01',
      assetName: equipmentName || req.body.assetName || 'Facility Equipment',
      title: title || 'Automated Maintenance Task',
      description: description || 'Generated by Agentic FacilityOps Engine.',
      priority: priority || 'Medium',
      assignedTechnician: assignedTechnician || 'Auto-Dispatched Field Lead',
      estimatedCostUsd: req.body.estimatedCostUsd || 1200,
      preventedDowntimeHrs: req.body.preventedDowntimeHrs || 24,
      generatedBy: req.body.generatedBy || 'Maintenance Agent',
      sparePartsRequired: req.body.sparePartsRequired || ['Standard Maintenance Kit'],
    };

    const savedWo = await createWorkOrderDb(newWo);
    return res.status(201).json({ success: true, workOrder: savedWo });
  } catch (error: any) {
    return res.status(500).json({ success: false, error: error.message || 'Failed to create work order' });
  }
}

export async function updateWorkOrder(req: Request, res: Response) {
  try {
    const { id } = req.params;
    const updateData: any = {};
    if (req.body.status) updateData.status = req.body.status;
    if (req.body.assignedTechnician) updateData.assignedTechnician = req.body.assignedTechnician;
    if (req.body.priority) updateData.priority = req.body.priority;

    const updated = await updateWorkOrderDb(id, updateData);

    if (!updated) {
      return res.status(404).json({ success: false, error: 'Work order not found' });
    }

    return res.json({ success: true, workOrder: updated });
  } catch (error: any) {
    return res.status(500).json({ success: false, error: error.message || 'Failed to update work order' });
  }
}

export async function getEquipmentHealth(req: Request, res: Response) {
  try {
    const equipment = await getEquipmentDb();
    return res.json({ success: true, equipment });
  } catch (error: any) {
    return res.status(500).json({ success: false, error: error.message || 'Failed to fetch equipment health' });
  }
}


